---
- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    region: "{{ region }}"
    environment: "{{ environment }}"

  roles:
    - role: eks

  vars_files:
    - vars/main.yml  
