# Default values for prometheus-operator.

prometheusOperator:
  nodeSelector:
    gcs-nodegroup-type: ng-operations
  tolerations:
    - key: "gcs-nodegroup-taint"
      operator: "Exists"
      #value: "ng-operations"
      #effect: "NoSchedule"

#Prometheus setup
prometheus:
  resources:
    limits:
      cpu: 300m
      memory: 500Mi
  prometheusSpec:
    nodeSelector:
      gcs-nodegroup-type: ng-operations
    tolerations:
      - key: "gcs-nodegroup-taint"
        operator: "Exists"
       # value: "ng-operations"
        #effect: "NoSchedule"
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: gp2
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi

# Define persistent storage for Grafana (PVC)
grafana:
  adminPassword: "Pitney!123"
  nodeSelector:
    gcs-nodegroup-type: ng-operations
  tolerations:
    - key: "gcs-nodegroup-taint"
      operator: "Exists"
      #value: "ng-operations"
     # effect: "NoSchedule"
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
  service:
    type: LoadBalancer
    port: 80
  persistence:
    enabled: true
    storageClassName: gp2
    accessModes: ["ReadWriteOnce"]
    size: 5Gi

# Define persistent storage for Alertmanager (PVC)
alertmanager:
  resources:
    limits:
      cpu: 100m
      memory: 256Mi
  alertmanagerSpec:
    nodeSelector:
      gcs-nodegroup-type: ng-operations
    tolerations:
      - key: "gcs-nodegroup-taint"
        operator: "Exists"
       # value: "ng-operations"
        #effect: "NoSchedule"
    storage:
      volumeClaimTemplate:
        spec:
          accessModes:
          - ReadWriteOnce
          storageClassName: gp2
          resources:
            requests:
              storage: 5Gi

# Change default node-exporter port
prometheus-node-exporter:
  service:
    port: 30206
    targetPort: 30206

# Disable Etcd metrics
kubeEtcd:
  enabled: false

# Disable Controller metrics
kubeControllerManager:
  enabled: false

# Disable Scheduler metrics
kubeScheduler:
  enabled: false
  
kubelet:
  serviceMonitor:
    https: false
  
kubeProxy:
  enabled: false
  
coreDns:
  enabled: false